name: listastic
description: Listastic is a real-time shoppinglist app.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^1.2.0
  firebase_analytics: ^8.1.0
  firebase_auth: ^1.2.0
  cloud_firestore: ^2.2.0
  cupertino_icons: ^1.0.2
  google_sign_in: ^5.0.3
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.2
  pedantic: ^1.11.0
  intl: ^0.17.0
  jiffy: ^4.1.0
  supercharged: ^2.0.0
  simple_animations: ^3.1.1
  sqflite: ^2.0.0+3
  shared_preferences: ^2.0.5
  email_validator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.0.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
